version: "2"

services:
  surveys:
    environment:
      - PYTHONUNBUFFERED=1
      - SURVEY_SECRET_KEY=${SURVEY_SECRET_KEY}
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
