openapi: 3.0.2
info:
  title: Survey service backend API
  version: 'v1'
paths:
  /api/:
    get:
      operationId: listapi_versions_lists
      description: "API endpoint \u0441\u043E \u0441\u043F\u0438\u0441\u043A\u043E\
        \u043C \u0434\u043E\u0441\u0442\u0443\u043F\u043D\u044B\u0445 \u0432\u0435\
        \u0440\u0441\u0438\u0439 API"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/:
    get:
      operationId: listapi_v1_roots
      description: "API endpoint \u043A\u043E\u0440\u043D\u0435\u0432\u043E\u0439\
        \ \u0434\u0438\u0440\u0435\u043A\u0442\u043E\u0440\u0438\u0438 APIv1"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/schemes/{id}/take:
    get:
      operationId: listscheme_takes
      description: "API endpoint \u0434\u043B\u044F \u0441\u043E\u0437\u0434\u0430\
        \u043D\u0438\u044F \u0444\u043E\u0440\u043C\u044B \u043E\u043F\u0440\u043E\
        \u0441\u0430"
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/surveys/:
    get:
      operationId: listSurveyLists
      description: "API endpoint \u0434\u043B\u044F \u043F\u0440\u043E\u0441\u043C\
        \u043E\u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430 \u043E\u043F\
        \u0440\u043E\u0441\u043E\u0432 \u0443\u0447\u0430\u0441\u0442\u043D\u0438\u043A\
        \u043E\u043C"
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Survey'
          description: ''
      tags:
      - api
  /api/v1/surveys/{id}:
    get:
      operationId: retrieveSurvey
      description: "API endpoint \u0434\u043B\u044F \u0437\u0430\u043F\u043E\u043B\
        \u043D\u0435\u043D\u0438\u044F \u043E\u043F\u0440\u043E\u0441\u0430 \u0443\
        \u0447\u0430\u0441\u0442\u043D\u0438\u043A\u043E\u043C"
      parameters:
      - name: id
        in: path
        required: true
        description: "A UUID string identifying this \u043F\u0440\u043E\u0439\u0434\
          \u0435\u043D\u043D\u044B\u0439 \u043E\u043F\u0440\u043E\u0441."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
          description: ''
      tags:
      - api
    put:
      operationId: updateSurvey
      description: "API endpoint \u0434\u043B\u044F \u0437\u0430\u043F\u043E\u043B\
        \u043D\u0435\u043D\u0438\u044F \u043E\u043F\u0440\u043E\u0441\u0430 \u0443\
        \u0447\u0430\u0441\u0442\u043D\u0438\u043A\u043E\u043C"
      parameters:
      - name: id
        in: path
        required: true
        description: "A UUID string identifying this \u043F\u0440\u043E\u0439\u0434\
          \u0435\u043D\u043D\u044B\u0439 \u043E\u043F\u0440\u043E\u0441."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Survey'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Survey'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Survey'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateSurvey
      description: "API endpoint \u0434\u043B\u044F \u0437\u0430\u043F\u043E\u043B\
        \u043D\u0435\u043D\u0438\u044F \u043E\u043F\u0440\u043E\u0441\u0430 \u0443\
        \u0447\u0430\u0441\u0442\u043D\u0438\u043A\u043E\u043C"
      parameters:
      - name: id
        in: path
        required: true
        description: "A UUID string identifying this \u043F\u0440\u043E\u0439\u0434\
          \u0435\u043D\u043D\u044B\u0439 \u043E\u043F\u0440\u043E\u0441."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Survey'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Survey'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Survey'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
          description: ''
      tags:
      - api
  /api/v1/participants/:
    get:
      operationId: listParticipants
      description: "API endpoint \u0441\u043F\u0438\u0441\u043A\u0430 \u0443\u0447\
        \u0430\u0441\u0442\u043D\u0438\u043A\u043E\u0432 \u043E\u043F\u0440\u043E\u0441\
        \u0430"
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Participant'
          description: ''
      tags:
      - api
  /api/v1/participants/{id}:
    get:
      operationId: retrieveParticipant
      description: "API endpoint \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\
        \u0438 \u043E\u0431 \u0443\u0447\u0430\u0441\u0442\u043D\u0438\u043A\u0435\
        \ \u043E\u043F\u0440\u043E\u0441\u0430"
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0443\u0447\u0430\u0441\
          \u0442\u043D\u0438\u043A \u043E\u043F\u0440\u043E\u0441\u0430."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Participant'
          description: ''
      tags:
      - api
components:
  schemas:
    AnswerOption:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        text:
          type: string
          maxLength: 255
      required:
        - text
    Question:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        text:
          type: string
          maxLength: 255
        answer_type:
          enum:
            - TEXT
            - SINGLE
            - MULTIPLE
          type: string
          maxLength: 127
        answer_options:
          type: array
          items:
            $ref: '#/components/schemas/AnswerOption'
      required:
        - text
        - answer_type
    Scheme:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        url:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type: string
        date_from:
          type: string
          format: date
          readOnly: true
        date_to:
          type: string
          format: date
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'
      required:
        - name
        - date_from
        - date_to
    Survey:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        url:
          type: string
          format: url
          readOnly: true
        participant:
          type: string
          readOnly: true
        scheme:
          type: string
          format: url
          readOnly: true
    Participant:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        url:
          type: string
          readOnly: true
        full_name:
          type: string
        results:
          type: array
          items:
            type: string
            format: url
