# Generated by Django 2.2.10 on 2020-11-29 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField(verbose_name='полное имя')),
            ],
            options={
                'verbose_name': 'участник опроса',
                'verbose_name_plural': 'участники опроса',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('date_from', models.DateField(default=datetime.date.today, editable=False, verbose_name='дата начала')),
                ('date_to', models.DateField(default=datetime.date.today, verbose_name='дата окончания')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
                'ordering': ['-date_from'],
                'unique_together': {('name', 'date_from')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='текст вопроса')),
                ('answer_type', models.CharField(choices=[('TEXT', 'ответ текстом'), ('SINGLE', 'ответ с выбором одного варианта'), ('MULTIPLE', 'ответ с выбором нескольких вариантов')], default='TEXT', max_length=127, verbose_name='тип ответа')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Scheme', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'unique_together': {('survey', 'text')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='содержание ответа')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Participant', verbose_name='участник опроса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
