# Generated by Django 2.2.10 on 2020-11-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_normalization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
    ]
