# Generated by Django 2.2.10 on 2020-12-01 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_del_question_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, verbose_name='содержание ответа'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='survey.Question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'вариант ответа на вопрос',
                'verbose_name_plural': 'варианты ответов на вопросы',
            },
        ),
    ]
